services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - WEATHER_API_BASE_URL=http://weather-service:8080
    depends_on:
      - weather-service

  weather-service:
    build:
      context: ./weather-service
      dockerfile: Dockerfile
    ports:
      - "5001:8080"

  superhero-service:
    build:
      context: ./superhero-service
      dockerfile: Dockerfile
    ports:
      - "5002:3000"
    environment:
      - SUPERHERO_DB_URL=jdbc:postgresql://superhero-db:5432/superhero

  superhero-db:
    image: postgres:17
    environment:
      DATABASE_URL: jdbc:postgresql://superhero-db:5432/superhero
    ports:
      - "5432:5432"