services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - WEATHER_API_BASE_URL=http://weather-service:8080
    depends_on:
      - weather-service

  weather-service:
    build:
      context: ./weather-service
      dockerfile: Dockerfile
    ports:
      - "5001:8080"