services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - WEATHER_API_BASE_URL=http://weather-service:8080
    depends_on:
      - weather-service

  weather-service:
    build:
      context: ./weather-service
      dockerfile: Dockerfile
    # ports:
    #   - "5001:8080"

  superhero-service:
    build:
      context: ./superhero-service
      dockerfile: Dockerfile
    depends_on:
      superhero-db:
        condition: service_healthy
        restart: true
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@superhero-db:5432/

  superhero-db:
    image: postgres:17
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s